[build]
  base = "web"
  command = "mkdir -p public && cp -R ../FloMarktGallerie public/ && npm ci && npm run build"
  publish = "web/dist"

[dev]
  framework = "#static"
  targetPort = 0

[images]
  remote_images = ["*"]


